export const searchData = [
  {
    title: "Home",
    description: "Go to the welcome page",
    path: "/",
    keywords: [
      "home",
      "cv",
      "resume",
      "start",
      "welcome",
      "portfolio",
      "niladri",
      "niladri chatterjee",
      "software developer",
      "full stack developer",
      "mern stack",
      "web developer",
    ],
  },
  {
    title: "About",
    description: "Learn more about me and my background",
    path: "/about",
    keywords: [
      "about",
      "background",
      "education",
      "bio",
      "profile",
      "cv",
      "resume",
      "niladri",
      "chatterjee",
      "full stack developer",
      "software engineer",
      "web developer",
    ],
  },
  {
    title: "Education",
    description: "View my educational background",
    path: "/education",
    keywords: [
      "education",
      "university",
      "college",
      "degree",
      "school",
      "board",
      "computer science",
      "engineering",
      "b.tech",
      "bengal college",
    ],
  },
  {
    title: "Experience",
    description: "Check out my professional experience",
    path: "/experience",
    keywords: [
      "experience",
      "work",
      "career",
      "jobs",
      "professional",
      "internships",
      "mern",
      "full stack",
      "software developer",
    ],
  },
  {
    title: "Skills",
    description: "Explore my technical skills and expertise",
    path: "/skills",
    keywords: [
      "skills",
      "technologies",
      "programming",
      "frameworks",
      "react",
      "node",
      "javascript",
      "typescript",
      "nextjs",
      "mongodb",
      "sql",
    ],
  },
  {
    title: "Projects",
    description: "View my portfolio of projects",
    path: "/projects",
    keywords: [
      "projects",
      "portfolio",
      "github",
      "code",
      "opensource",
      "react",
      "node",
      "mern",
    ],
  },
  {
    title: "Certificates",
    description: "View my certifications and achievements",
    path: "/certificates",
    keywords: [
      "certificates",
      "certifications",
      "achievements",
      "courses",
      "learning",
      "awards",
      "badges",
    ],
  },
  {
    title: "Contact",
    description: "Get in touch with me",
    path: "/contact",
    keywords: [
      "contact",
      "email",
      "hire",
      "freelance",
      "collaboration",
      "job",
      "opportunity",
			"number",
			"phone"
    ],
  },
];
